#pragma once
#include "RenderEngine.h"
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/gtx/vector_angle.hpp>
#include <SOIL/SOIL.h>

class Demo :
	public RenderEngine
{
public:
	Demo();
	~Demo();
private:
	GLuint shaderProgram, VBO, VAO, EBO, texture, VBO2, VAO2, EBO2, texture2, VBO3, VAO3, EBO3, texture3, VBO4, VAO4, EBO4, texture4, VBO5, VAO5, EBO5, texture5, VBO6, VAO6, EBO6, texture6, VBO7, VAO7, EBO7, texture7, VBO8, VAO8, EBO8, texture8, VBO9, VAO9, EBO9, texture9, VBO10, VAO10, EBO10, texture10, VBO11, VAO11, EBO11, texture11, VBO12, VAO12, EBO12, texture12, VBO13, VAO13, EBO13, texture13, VBO14, VAO14, EBO14, texture14, VBO15, VAO15, EBO15, texture15, VBO16, VAO16, EBO16, texture16, VBO17, VAO17, EBO17, texture17, VBO18, VAO18, EBO18, texture18, VBO19, VAO19, EBO19, texture19, VBO20, VAO20, EBO20, texture20, VBO21, VAO21, EBO21, texture21, VBO22, VAO22, EBO22, texture22, VBO23, VAO23, EBO23, texture23, VBO24, VAO24, EBO24, texture24, VBO25, VAO25, EBO25, texture25, VBO26, VAO26, EBO26, texture26, VBO27, VAO27, EBO27, texture27, VBO28, VAO28, EBO28, texture28, VBO29, VAO29, EBO29, texture29, VBO30, VAO30, EBO30, texture30, VBO31, VAO31, EBO31, texture31, VBO32, VAO32, EBO32, texture32, VBO33, VAO33, EBO33, texture33, VBO34, VAO34, EBO34, texture34, stexturepapan, stexturelukisan;
	float viewCamX, viewCamY, viewCamZ, upCamX, upCamY, upCamZ, posCamX, posCamY, posCamZ, CAMERA_SPEED, fovy;
	float angleKipas = 0;
	virtual void Init();
	virtual void DeInit();
	virtual void Update(double deltaTime);
	virtual void Render();
	virtual void ProcessInput(GLFWwindow* window);
	void BuildLukisanADepan();
	void BuildLukisanBDepan();
	void BuildLukisanCDepan();
	void BuildLukisanBingkai();
	void BuildPilar();
	void BuildDindingA();
	void BuildDindingB();
	void BuildDindingC();
	void BuildDindingKanan();
	void BuildLukisanKananA();
	void BuildLukisanKananB();
	void BuildPapanTulis();
	void BuildPapanTulisBorder();
	void BuildPintuBingkai();
	void BuildLantai();
	void BuildPintu();
	void BuildLukisanKananC();
	void BuildLukisanKananBingkai();
	void BuildSaklar();
	void BuildSaklarBorder();
	void BuildDindingBelakang();
	void BuildAtap();
	void BuildVentilasiDepan();
	void BuildVentilasiBorder();
	void BuildLampuDepan();
	void BuildLampuBorder();
	void BuildKanopiKipas();
	void BuildLeherKipas();
	void BuildKipas();
	void BuildMeja();
	void BuildKakiKursi();
	void BuildKursi();
	void BuildLaptop();
	void BuildLaptopDepan();
	void DrawLukisanADepan();
	void DrawLukisanBDepan();
	void DrawLukisanCDepan();
	void DrawLukisanBingkai();
	void DrawLukisanBBingkai();
	void DrawLukisanCBingkai();
	void DrawPilarDepanKiri();
	void DrawPilarDepanKanan();
	void DrawPilarKiriDepan();
	void DrawPilarKiriBelakang();
	void DrawPilarKananDepan();
	void DrawPilarKananBelakang();
	void DrawPilarBelakangKiri();
	void DrawPilarBelakangKanan();
	void DrawDindingKiriPapan();
	void DrawDindingKananPapan();
	void DrawDindingKiriBelakang();
	void DrawDindingKananBelakang();
	void DrawDindingBelakangPapan();
	void DrawDindingKiri();
	void DrawDindingKanan();
	void DrawLukisanKananA();
	void DrawLukisanKananB();
	void DrawPapanTulis();
	void DrawPapanTulisBorder();
	void DrawPintuBingkai();
	void DrawLantai();
	void DrawPintu();
	void DrawLukisanKananC();
	void DrawLukisanKananABingkai();
	void DrawLukisanKananBBingkai();
	void DrawLukisanKananCBingkai();
	void DrawSaklar();
	void DrawSaklarBorder();
	void DrawDindingBelakang();
	void DrawAtap();
	void DrawVentilasiDepanA();
	void DrawVentilasiDepanB();
	void DrawVentilasiBorderA();
	void DrawVentilasiBorderB();
	void DrawLampuDepan();
	void DrawLampuBorder();
	void DrawKanopiKipasA();
	void DrawKanopiKipasB();
	void DrawLeherKipasA();
	void DrawLeherKipasB();
	void DrawKipasA();
	void DrawKipasB();
	void DrawMeja();
	void DrawKakiKursiA();
	void DrawKakiKursiB();
	void DrawKakiKursiC();
	void DrawKakiKursiD();
	void DrawKakiKursiE();
	void DrawKakiKursiF();
	void DrawKakiKursiG();
	void DrawKakiKursiH();
	void DrawKakiKursiI();
	void DrawKakiKursiJ();
	void DrawKakiKursiK();
	void DrawKursiA();
	void DrawKursiB();
	void DrawKursiC();
	void DrawKursiD();
	void DrawKursiE();
	void DrawKursiF();
	void DrawKursiG();
	void DrawKursiH();
	void DrawKursiI();
	void DrawKursiJ();
	void DrawKursiK();
	void DrawLaptopA();
	void DrawLaptopB();
	void DrawLaptopC();
	void DrawLaptopD();
	void DrawLaptopE();
	void DrawLaptopF();
	void DrawLaptopG();
	void DrawLaptopH();
	void DrawLaptopI();
	void DrawLaptopJ();
	void DrawLaptopK();
	void DrawLaptopDepanA();
	void DrawLaptopDepanB();
	void DrawLaptopDepanC();
	void DrawLaptopDepanD();
	void DrawLaptopDepanE();
	void DrawLaptopDepanF();
	void DrawLaptopDepanG();
	void DrawLaptopDepanH();
	void DrawLaptopDepanI();
	void DrawLaptopDepanJ();
	void DrawLaptopDepanK();
	void MoveCamera(float speed);
	void StrafeCamera(float speed);
	void VerticalCamera(float speed);
	void RotateCamera(float speed);
	void InitCamera();
};

